timezone: null
custom_base_url: null
http_x_forwarded:
  protocol: true
  port: true
  ip: true
languages:
  supported:
    - de
home:
  alias: /inhaltsverzeichnis
pages:
  theme: learn4
  process:
    markdown: true
    twig: false
  append_url_extension: null
  etag: false
  redirect_default_code: '302'
cache:
  clear_images_by_default: true
  redis:
    socket: null
twig:
  autoescape: false
  umask_fix: false
assets:
  collections:
    jquery: 'system://assets/jquery/jquery-2.x.min.js'
debugger:
  twig: true
images:
  auto_fix_orientation: false
  cls:
    retina_scale: '1'
media:
  upload_limit: 262144000
gpm:
  proxy_url: null
  method: auto
  verify_peer: true
accounts:
  type: data
strict_mode:
  yaml_compat: true
  blueprint_compat: true
  twig_compat: true
