enabled: true
top_level_version: false
github:
  position: 'off'
streams:
  schemes:
    theme:
      type: ReadOnlyStream
      prefixes:
        '': [user/themes/learn2-git-sync, user/themes/learn2]
